/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function log(n: number): void
export class MyBTree {
  constructor()
  static newRandom(size: number): MyBTree
  insert(key: number, value: number): void
  find(key: number): number | null
  remove(key: number): void
}
